# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{harvestr}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wynn Netherland", "Jim Mulholland", "Jason Derrett"]
  s.date = %q{2009-11-16}
  s.email = %q{jim@squeejee.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History",
     "License",
     "Notes",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "examples/time_tracking.rb",
     "lib/harvest/base.rb",
     "lib/harvest/reports.rb",
     "lib/harvest/time_tracking.rb",
     "lib/harvestr.rb",
     "test/fixtures/daily.xml",
     "test/fixtures/entry.xml",
     "test/fixtures/project_entries.xml",
     "test/fixtures/rate_limit_status.xml",
     "test/fixtures/timer_toggle.xml",
     "test/fixtures/update_entry.xml",
     "test/harvestr/base_test.rb",
     "test/harvestr/reports_test.rb",
     "test/harvestr/time_tracking_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/squeejee/harvestr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{harvestr}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{wrapper for the Harvest api}
  s.test_files = [
    "test/harvestr/base_test.rb",
     "test/harvestr/reports_test.rb",
     "test/harvestr/time_tracking_test.rb",
     "test/test_helper.rb",
     "examples/time_tracking.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mash>, ["= 0.0.3"])
      s.add_runtime_dependency(%q<httparty>, ["= 0.4.3"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<jeremymcanally-matchy>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, ["= 1.2.5"])
      s.add_development_dependency(%q<mash>, [">= 0"])
    else
      s.add_dependency(%q<mash>, ["= 0.0.3"])
      s.add_dependency(%q<httparty>, ["= 0.4.3"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<jeremymcanally-matchy>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<fakeweb>, ["= 1.2.5"])
      s.add_dependency(%q<mash>, [">= 0"])
    end
  else
    s.add_dependency(%q<mash>, ["= 0.0.3"])
    s.add_dependency(%q<httparty>, ["= 0.4.3"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<jeremymcanally-matchy>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<fakeweb>, ["= 1.2.5"])
    s.add_dependency(%q<mash>, [">= 0"])
  end
end

